name: Local Config
version: 1.0.0
schema: v1
models:
  - name: Ollama Local
    provider: ollama
    model: autodetect

  - name: OPEN_AI_KEY    # Must match the secret name exactly
    provider: openai
    model: gpt-3.5-turbo
